AWSTemplateFormatVersion: '2010-09-09'
Description: 'Internet Gateway and NAT Gateway CloudFormation Template'

Parameters:
  VPCStackName:
    Type: String
    Default: vpc-stack
    Description: Name of the VPC stack to import values from

Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !ImportValue
        Fn::Sub: "${VPCStackName}-VPC-ID"
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue
        Fn::Sub: "${VPCStackName}-VPC-ID"
      Tags:
        - Key: Name
          Value: PublicRouteTable

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !ImportValue
        Fn::Sub: "${VPCStackName}-PublicSubnet1-ID"
      RouteTableId: !Ref PublicRouteTable

Outputs:
  InternetGatewayId:
    Description: Internet Gateway ID
    Value: !Ref InternetGateway
    Export:
      Name: !Sub "${VPCStackName}-InternetGateway-ID"
