AWSTemplateFormatVersion: '2010-09-09'
Description: 'Internet Gateway and NAT Gateway CloudFormation Template'

Parameters:
  VPCStackName:
    Type: String
    Default: vpc-stack
    Description: Name of the VPC stack to import values from

Resources:
  NATGatewayEIP:
    Type: AWS::EC2::EIP
    DependsOn: AttachGateway
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: NATGatewayEIP

  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NATGatewayEIP.AllocationId
      SubnetId: !ImportValue
        Fn::Sub: "${VPCStackName}-PublicSubnet1-ID"
      Tags:
        - Key: Name
          Value: NATGateway

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue
        Fn::Sub: "${VPCStackName}-VPC-ID"
      Tags:
        - Key: Name
          Value: PrivateRouteTable

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway

  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !ImportValue
        Fn::Sub: "${VPCStackName}-PrivateSubnet1-ID"
      RouteTableId: !Ref PrivateRouteTable

Outputs:
  NATGatewayId:
    Description: NAT Gateway ID
    Value: !Ref NATGateway
    Export:
      Name: !Sub "${VPCStackName}-NATGateway-ID"